name: run-tests
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get -y install python-software-properties
      - run: sudo add-apt-repository ppa:ondrej/php
      - run: sudo apt-get update && sudo apt-get install -y php5.6
      - run: php -v
  
